# Generated by Django 2.2.4 on 2019-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PREMISSAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(max_length=40)),
                ('reducao', models.CharField(max_length=40)),
                ('extensao1', models.CharField(max_length=20)),
                ('termo1', models.CharField(max_length=100)),
                ('termo2', models.CharField(max_length=100)),
                ('extensao2', models.CharField(max_length=20)),
                ('termo3', models.CharField(max_length=100)),
                ('termo4', models.CharField(max_length=100)),
                ('extensao3', models.CharField(max_length=20)),
                ('termo5', models.CharField(max_length=100)),
                ('termo6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='REDUCAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid_silogismo', models.IntegerField()),
                ('sid_reducao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SINTASSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('sintasse', models.CharField(max_length=288)),
            ],
        ),
    ]
