# Generated by Django 2.2.4 on 2019-08-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_sintasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SINTASSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('sin_p1', models.CharField(max_length=288)),
                ('sin_p2', models.CharField(max_length=288)),
                ('sin_c', models.CharField(max_length=288)),
            ],
        ),
    ]
