# Generated by Django 2.2.4 on 2019-08-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_sintasse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PREMISSAS',
        ),
    ]
