# Generated by Django 2.2.4 on 2019-08-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_premissas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err_sid', models.IntegerField()),
                ('err_erro', models.CharField(max_length=50)),
            ],
        ),
    ]
