# Generated by Django 2.2.4 on 2019-08-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_CLASSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_codigo', models.CharField(max_length=64)),
            ],
        ),
    ]
