# Generated by Django 2.2.4 on 2019-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_e_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='premissas',
            name='clsse',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
