# Generated by Django 2.2.4 on 2019-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190819_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='erro',
            name='err_classe',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
