# Generated by Django 2.2.4 on 2019-08-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_erro_err_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_classe',
            name='e_pro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
